### ISSUE TITLE
Allow users to get a stream of all key presses by not providing an argument

### ISSUE THREAD

**Issue by raquelxmoss** [raquelxmoss/cycle-keys#2]

**Comment by krainboltgreene** [comment]
This is definitely relevant to my interest!

**Comment by raquelxmoss** [comment]
@krainboltgreene I've released v0.1.0 which supports this. You can now get a stream of all keypress events by calling `Keys.presses()` without any arguments. 😸

**Comment by krainboltgreene** [comment]
Woot! Dropping it in immediately :D Thanks so much!

Also, you should consider marking this library as v1.0.0! I'm currently using it in production :)

**Comment by raquelxmoss** [comment]
That's fantastic @krainboltgreene! I'll do a little more work on it this week and then bump the version.
